name: Safe Settings Sync

# on:
#   schedule:
#     - cron: "0 */24 * * *"
#   push: 
#     branches:
#       - 'main'
#   workflow_dispatch: {}

jobs:
  safeSettingsSync:
    runs-on: ubuntu-latest
    env:
      SAFE_SETTINGS_CODE_DIR: ./safe-settings
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: github/safe-settings
          path: ${{ env.SAFE_SETTINGS_CODE_DIR }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
        working-directory: ${{ env.SAFE_SETTINGS_CODE_DIR }}
      - run: npm run full-sync
        working-directory: ${{ env.SAFE_SETTINGS_CODE_DIR }}
        env:
          GH_ORG: 'durman16'
          APP_ID: '1697548'
          PRIVATE_KEY: ${{ secrets.SAFE_SETTINGS_PRIVATE_KEY }}
          GITHUB_CLIENT_ID: 'Iv23liXx5OjAEFocs8wh'
          GITHUB_CLIENT_SECRET: 'f2dbb5f6124b9474a492a771a65a9a91564eb59c'
